name: Backend-test

on:
  push:
    branches: [ main,develop ]

  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    environment: vms
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: "Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: "Install Dependencies"
        working-directory: ./fresh-produce-inventory-tracker
        run: npm ci

      - name: "ğŸ Run tests backend"
        working-directory: ./fresh-produce-inventory-tracker
        run: npm run test
